{% set name = "openmmtools" %}
{% set version = "0.22.2_dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/choderalab/openmmtools/archive/{{ version }}.tar.gz
  git_rev: 252ec6203c979f9714f62845aa77f277be0efc9e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  noarch: python
  entry_points:
    - test-openmm-platforms = openmmtools.scripts.test_openmm_platforms:main
    - benchmark-alchemy = openmmtools.tests.test_alchemy:benchmark_alchemy_from_pdb

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - hdf5 =1.12.*
    - libnetcdf >=4.6.2
    - mdtraj
    - mpiplus
    - netcdf4 >=1.5
    - nose
    - numba
    - numpy >=1.14
    - openmm >=7.3.1
    - pandas
    - pdbfixer
    - pymbar
    - python >=3.8
    - pyyaml
    - scipy
    - setuptools

test:
  imports:
    - openmmtools
  commands:
    - test-openmm-platforms --help
    - benchmark-alchemy --help

about:
  home: https://github.com/choderalab/openmmtools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A batteries-included toolkit for the GPU-accelerated OpenMM molecular simulation engine.
  description: |
    openmmtools is a Python library layer that sits on top of OpenMM to provide access
    to a variety of useful tools for building full-featured molecular simulation packages.
  doc_url: https://openmmtools.readthedocs.io
  dev_url: https://github.com/choderalab/openmmtools

extra:
  recipe-maintainers:
    - jaimergp
    - jchodera
    - mikemhenry
    - ijpulidos
