{% set name = "openmmtools" %}
{% set version = "0.25.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/openmmtools/archive/{{ version }}.tar.gz
  sha256: 2f5c5e89d47219a0f78cd0a252593b34575c997f27269c365dc319078a8bcdb1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  noarch: python
  entry_points:
    - test-openmm-platforms = openmmtools.scripts.test_openmm_platforms:main
    - benchmark-alchemy = openmmtools.tests.test_alchemy:benchmark_alchemy_from_pdb

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - hdf5
    - libnetcdf >=4.6.2
    - mdtraj
    - mpiplus
    - netcdf4 >=1.5
    - numba
    - numpy >1.9
    - openmm >=7.3.1
    - pandas
    - pdbfixer
    - pymbar
    - python >={{ python_min }}
    - pyyaml
    - scipy  >=1.15.0
    - setuptools

test:
  requires:
    - python {{ python_min }}
    - pytest
    - requests
    - coverage
  imports:
    - openmmtools
  commands:
    - pytest --pyargs openmmtools
    - test-openmm-platforms --help
    - benchmark-alchemy --help

about:
  home: https://github.com/choderalab/openmmtools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A batteries-included toolkit for the GPU-accelerated OpenMM molecular simulation engine.
  description: |
    openmmtools is a Python library layer that sits on top of OpenMM to provide access
    to a variety of useful tools for building full-featured molecular simulation packages.
  doc_url: https://openmmtools.readthedocs.io
  dev_url: https://github.com/choderalab/openmmtools

extra:
  recipe-maintainers:
    - jaimergp
    - jchodera
    - mikemhenry
    - ijpulidos
